name: Pruebas Unitarias

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependencias principales
        run: npm install

      - name: Instalar Jest
        run: npm install --save-dev jest

      - name: Instalar jsdom
        run: npm install --save-dev jsdom

      - name: Ejecutar pruebas
        run: npx jest
